### ISSUE TITLE
I don't understand how the v2-0 works

### ISSUE THREAD

**Issue by giuliomagnifico** [supermamon/scriptable-instagram-widgets#1]
Sorry but I can't figure out out the v2.0 works, I have updated the code on the widget but is blank because it need the _InstagramClient.js_ but the "import" link doesn't work and if i manually import and run the _InstagramClient.js_ it gives me an error: `Error on line 48:25: TypeError: null is not an object (evaluating 'req.response.cookies.forEach')`, also put it inside the Cache folder doesn't work. A small tutorial would be usefuel! Thanks :)

**Comment by marcoPL2310** [comment]
Same here

**Comment by supermamon** [comment]
I've updated the script to v2.0.1. Hopefully that fixes the issue. If the issue remains, try deleting the `/Scriptable/cache/igclient/session.json` file then running the script again.

**Comment by supermamon** [comment]
fixed by 5f1f4d919266a1a619b877d89d16d71ef51480c6.

**Comment by supermamon** [comment]
> because it need the _InstagramClient.js_ 

@giuliomagnifico, it does not need `InstagramClient.js`. The code for that is already included in `ig-latest-post.js`.

**Comment by giuliomagnifico** [comment]
Okay the v2.0.1 fixed it and works fine. Thanks!
